name: code_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

#language
flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  google_fonts: ^2.3.2
  sizer: ^2.0.15
  flutter_bloc: ^8.0.1
  yaml: ^3.1.1
  dio: ^4.0.6
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  internet_connection_checker: ^0.0.1+3
  auto_route: ^4.0.1
  flutter_native_splash: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  device_preview: ^1.0.0
  build_runner: ^2.1.11
  auto_route_generator: ^4.0.0

## Json serializable config
targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          #          disallow_unrecognized_keys: false
          disallow_unrecognized_keys: true
          explicit_to_json: false
          #          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - google_fonts/
    - assets/config/

